eureka.instance.lease-renewal-interval-in-seconds: 5
eureka.client.registry-fetch-interval-seconds: 5
eureka.instance.lease-expiration-duration-in-seconds: 60
server.port: 8000
eureka.client.register-with-eureka: true
eureka.client.fetch-registry: true
eureka.client.serviceUrl.defaultZone: http://ek1.com:7900/eureka/
#spring:
#  application:
#    name: eureka-client
eureka:
  instance:
    appname: eureka-client
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
